/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define STORAGE_T %in_out_t%
#define TYPE_IN_OUT %in_out_t_type%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    DOUBLE min;
    DOUBLE max;
    uint nanMode;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<STORAGE_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<STORAGE_T, RANK> inputData;

#define COMP_T %in_out_t_comp%

void main() {
    uint[RANK] index;
    getDispatchIndex(outputData, index);

    STORAGE_T valueRaw;
    tensorReadARM(inputData, index, valueRaw);

    COMP_T value = DECODE_STORAGE_TO_COMP(valueRaw, TYPE_IN_OUT, COMP_T);
    COMP_T minValue = COMP_T(pushConstants.min);
    COMP_T maxValue = COMP_T(pushConstants.max);

#if IS_BFLOAT(TYPE_IN_OUT)
    if (minValue > maxValue) {
        minValue = decode_to_f32(bfloat16_t(uint16_t(pushConstants.min)));
        maxValue = decode_to_f32(bfloat16_t(uint16_t(pushConstants.max)));
    }
#endif

#if IS_FLOAT(TYPE_IN_OUT) || IS_BFLOAT(TYPE_IN_OUT)
    if (isnan(value) && (pushConstants.nanMode == NAN_MODE_IGNORE)) {
        value = minValue;
    }

    value = isnan(float(value)) ? value : clamp(value, minValue, maxValue);
#else
    value = clamp(value, minValue, maxValue);
#endif

    tensorWriteARM(outputData, index, ENCODE_COMP_TO_STORAGE(value, STORAGE_T, TYPE_IN_OUT));
}
