/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_OUT_T %in_out_t%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    uint32_t axis;
    uint32_t offset;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<IN_OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_OUT_T, RANK> inputData;

void main() {
    uint[RANK] index;
    getDispatchIndex(inputData, index);

    uint[RANK] outputIndex;
    for (uint i = 0; i < outputIndex.length(); i++) {
        outputIndex[i] = index[i];
    }

    outputIndex[PUSH_UINT(0, axis)] += PUSH_UINT(1, offset);

    IN_OUT_T value;
    tensorReadARM(inputData, index, value);
    tensorWriteARM(outputData, outputIndex, value);
}
