/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%
#define WEIGHT_T %weight_t%
#define TYPE_IN %in_t_type%
#define TYPE_WEIGHT %weight_t_type%
#define TYPE_OUT %out_t_type%
#define TYPE_ACC %acc_t_type%
#define ACC_T %acc_t%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint;
    int32_t weightZeroPoint;
    int32_t pad[6];             // [d0, d1, top, bottom, left, right]
    int32_t stride[3];          // [d, y, x]
    int32_t dilation[3];        // [d, y, x]
} pushConstants;

layout(set = 0, binding = 0) uniform tensorARM<OUT_T, 5> outputData;       // [N, OD, OH, OW, OC]
layout(set = 1, binding = 0) uniform tensorARM<IN_T, 5> inputData;         // [N, ID, IH, IW, IC]
layout(set = 2, binding = 0) uniform tensorARM<WEIGHT_T, 5> weightsData;   // [OC, KD, KH, KW, IC]
layout(set = 3, binding = 0) uniform tensorARM<OUT_T, 1> biasesData;       // [BC]

void main() {
    uint[5] index;
    getDispatchIndex5(outputData, index);

    ACC_T acc = ACC_T(0);

    uint n = index[0];
    uint od = index[1];
    uint oy = index[2];
    uint ox = index[3];
    uint oc = index[4];

    int id = int(od) * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_8, PUSH_WORD_9, PUSH_WORD_10)[0] : pushConstants.stride[0]) - (PUSH_WORDS_VALID != 0 ? int[6](PUSH_WORD_2, PUSH_WORD_3, PUSH_WORD_4, PUSH_WORD_5, PUSH_WORD_6, PUSH_WORD_7)[0] : pushConstants.pad[0]);
    int iy = int(oy) * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_8, PUSH_WORD_9, PUSH_WORD_10)[1] : pushConstants.stride[1]) - (PUSH_WORDS_VALID != 0 ? int[6](PUSH_WORD_2, PUSH_WORD_3, PUSH_WORD_4, PUSH_WORD_5, PUSH_WORD_6, PUSH_WORD_7)[2] : pushConstants.pad[2]);
    int ix = int(ox) * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_8, PUSH_WORD_9, PUSH_WORD_10)[2] : pushConstants.stride[2]) - (PUSH_WORDS_VALID != 0 ? int[6](PUSH_WORD_2, PUSH_WORD_3, PUSH_WORD_4, PUSH_WORD_5, PUSH_WORD_6, PUSH_WORD_7)[4] : pushConstants.pad[4]);

    int KD = int(tensorSizeARM(weightsData, 1));
    int KH = int(tensorSizeARM(weightsData, 2));
    int KW = int(tensorSizeARM(weightsData, 3));
    int IC = int(tensorSizeARM(weightsData, 4));

    int ID = int(tensorSizeARM(inputData, 1));
    int IH = int(tensorSizeARM(inputData, 2));
    int IW = int(tensorSizeARM(inputData, 3));

    int dStart = id;
    int kdStart = 0;
    if (dStart < 0) {
        int delta = -dStart;
        kdStart = (delta + (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[0] : pushConstants.dilation[0]) - 1) / (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[0] : pushConstants.dilation[0]);
        dStart = id + kdStart * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[0] : pushConstants.dilation[0]);
    }

    int yStart = iy;
    int kyStart = 0;
    if (yStart < 0) {
        int delta = -yStart;
        kyStart = (delta + (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[1] : pushConstants.dilation[1]) - 1) / (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[1] : pushConstants.dilation[1]);
        yStart = iy + kyStart * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[1] : pushConstants.dilation[1]);
    }

    int xStart = ix;
    int kxStart = 0;
    if (xStart < 0) {
        int delta = -xStart;
        kxStart = (delta + (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[2] : pushConstants.dilation[2]) - 1) / (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[2] : pushConstants.dilation[2]);
        xStart = ix + kxStart * (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[2] : pushConstants.dilation[2]);
    }

    for (int d = dStart, kd = kdStart; kd < KD && d < ID; ++kd, d += (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[0] : pushConstants.dilation[0])) {
        for (int y = yStart, ky = kyStart; ky < KH && y < IH; ++ky, y += (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[1] : pushConstants.dilation[1])) {
            for (int x = xStart, kx = kxStart; kx < KW && x < IW; ++kx, x += (PUSH_WORDS_VALID != 0 ? int[3](PUSH_WORD_11, PUSH_WORD_12, PUSH_WORD_13)[2] : pushConstants.dilation[2])) {
                for (int ic = 0; ic < IC; ++ic) {
                    IN_T inputValue;
                    tensorReadARM(inputData, uint[](n, uint(d), uint(y), uint(x), uint(ic)), inputValue);

                    WEIGHT_T weightValue;
                    tensorReadARM(weightsData, uint[](oc, uint(kd), uint(ky), uint(kx), uint(ic)), weightValue);

                    ACC_T val = CONV_TO_ACC_INPUT(inputValue) - ACC_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_0 : pushConstants.inputZeroPoint));
                    ACC_T wt = CONV_TO_ACC_WEIGHT(weightValue) - ACC_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_1 : pushConstants.weightZeroPoint));
                    acc += val * wt;
                }
            }
        }
    }

    OUT_T bias;
    tensorReadARM(biasesData, uint[](tensorSizeARM(biasesData, 0) == 1 ? 0 : oc), bias);
    ACC_T bias_acc = CONV_TO_ACC_BIAS(bias);
    ACC_T sum = bias_acc + acc;
    OUT_T outVal = CONV_ACC_TO_OUT(sum);

    tensorWriteARM(outputData, index, outVal);
}
