/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%
#define RESCALE_TAIL %rescale_tail%
#if RESCALE_TAIL
#define TAIL_OUT_T %tail_out_t%
#define TAIL_MUL_T %tail_mul_t%
#define TAIL_OUT_LOWEST %tail_out_t_lowest%
#define TAIL_OUT_MAX %tail_out_t_max%
#define OUTPUT_T TAIL_OUT_T
RESCALE_TAIL_DECLARE(4, 5)
#else
#define OUTPUT_T OUT_T
#endif
#define WEIGHT_T %weight_t%
#define TYPE_IN %in_t_type%
#define TYPE_WEIGHT %weight_t_type%
#define TYPE_OUT %out_t_type%
#define TYPE_ACC %acc_t_type%
#define ACC_T %acc_t%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint;
    int32_t weightZeroPoint;
    int32_t pad[4];
    int32_t stride[2];
    int32_t dilation[2];
} pushConstants;

layout(set = 0, binding = 0) uniform tensorARM<OUTPUT_T, 4> outputData;    // [N, OH, OW, C * M]
layout(set = 1, binding = 0) uniform tensorARM<IN_T, 4> inputData;         // [N, H, W, C]
layout(set = 2, binding = 0) uniform tensorARM<WEIGHT_T, 4> weightsData;   // [KH, KW, C, M]
layout(set = 3, binding = 0) uniform tensorARM<OUT_T, 1> biasesData;       // [BC]

void main() {
    uint[4] index;
    getDispatchIndex4(outputData, index);

    const uint n = index[0];
    const uint oy = index[1];
    const uint ox = index[2];
    const uint ocm = index[3];
    const uint c = ocm / tensorSizeARM(weightsData, 3);
    const uint m = ocm % tensorSizeARM(weightsData, 3);

    const uint iy = oy * PUSH_INT(6, stride[0]) - PUSH_INT(2, pad[0]);
    const uint ix = ox * PUSH_INT(7, stride[1]) - PUSH_INT(4, pad[2]);

    ACC_T acc = ACC_T(0);

    for (uint ky = 0; ky < tensorSizeARM(weightsData, 0); ky++) {
        for (uint kx = 0; kx < tensorSizeARM(weightsData, 1); kx++) {
            const uint y = iy + ky * PUSH_INT(8, dilation[0]);
            const uint x = ix + kx * PUSH_INT(9, dilation[1]);

            if (y < tensorSizeARM(inputData, 1) && x < tensorSizeARM(inputData, 2)) {
                IN_T tempValue;
                uint index[] = {n, y, x, c};
                tensorReadARM(inputData, index, tempValue);
                ACC_T value = CONV_TO_ACC_INPUT(tempValue);

                WEIGHT_T tempWeight;
                uint weightIndex[] = {ky, kx, c, m};
                tensorReadARM(weightsData, weightIndex, tempWeight);
                ACC_T weight = CONV_TO_ACC_WEIGHT(tempWeight);

                ACC_T outValue = ACC_T(value) - ACC_T(PUSH_INT(0, inputZeroPoint));
                ACC_T outWeight = ACC_T(weight) - ACC_T(PUSH_INT(1, weightZeroPoint));

                acc += outValue * outWeight;
            }
        }
    }

    OUT_T bias;
    tensorReadARM(biasesData, uint[](tensorSizeARM(biasesData, 0) == 1 ? 0 : ocm), bias);
    ACC_T bias_acc = CONV_TO_ACC_BIAS(bias);
    ACC_T sum = bias_acc + acc;
    OUT_T outVal = CONV_ACC_TO_OUT(sum);

#if RESCALE_TAIL
    TAIL_OUT_T tailValue;
    rescaleTail(outVal, ocm, tailValue)
    tensorWriteARM(outputData, index, tailValue);
#else
    tensorWriteARM(outputData, index, outVal);
#endif
}
