/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%
#define TYPE_IN %in_t_type%
#define TYPE_OUT %out_t_type%

#if IS_FLOAT8(TYPE_IN) || IS_FLOAT8(TYPE_OUT)
    #define COMP_T float16_t
#elif IS_BFLOAT(TYPE_IN) || IS_BFLOAT(TYPE_OUT)
    #define COMP_T float
#else
    #define COMP_T OUT_T
#endif

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint1;
    int32_t inputZeroPoint2;
} pushConstants;

layout(set = 0, binding = 0) uniform tensorARM<OUT_T, 3> outputData;   // [N, H, W]
layout(set = 1, binding = 0) uniform tensorARM<IN_T, 3> inputData1;    // [N, H, C]
layout(set = 2, binding = 0) uniform tensorARM<IN_T, 3> inputData2;    // [N, C, W]

void main() {
    uint[3] index;
    getDispatchIndex3(outputData, index);

    uint on = index[0];
    uint oy = index[1];
    uint ox = index[2];

    COMP_T acc = COMP_T(0);

    const uint IC = tensorSizeARM(inputData1, 2);

    uint c = 0;
    for (; c + 3 < IC; c += 4) {
        IN_T value1[4];
        tensorReadARM(inputData1, uint[](on, oy, c), value1);

        IN_T value20, value21, value22, value23;
        tensorReadARM(inputData2, uint[](on, c, ox), value20);
        tensorReadARM(inputData2, uint[](on, c + 1, ox), value21);
        tensorReadARM(inputData2, uint[](on, c + 2, ox), value22);
        tensorReadARM(inputData2, uint[](on, c + 3, ox), value23);
        IN_T value2[4] = {value20, value21, value22, value23};

        for (uint idx = 0; idx < 4; ++idx) {
            COMP_T val1 = DECODE_STORAGE_TO_COMP(value1[idx], TYPE_IN, COMP_T) - COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_0 : pushConstants.inputZeroPoint1));
            COMP_T val2 = DECODE_STORAGE_TO_COMP(value2[idx], TYPE_IN, COMP_T) - COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_1 : pushConstants.inputZeroPoint2));
            acc += val1 * val2;
        }
    }

    for (; c < IC; ++c) {
        IN_T v1, v2;
        tensorReadARM(inputData1, uint[](on, oy, c), v1);
        tensorReadARM(inputData2, uint[](on, c, ox), v2);

        COMP_T val1 = DECODE_STORAGE_TO_COMP(v1, TYPE_IN, COMP_T) - COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_0 : pushConstants.inputZeroPoint1));
        COMP_T val2 = DECODE_STORAGE_TO_COMP(v2, TYPE_IN, COMP_T) - COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_1 : pushConstants.inputZeroPoint2));
        acc += val1 * val2;
    }

    OUT_T outValue = ENCODE_COMP_TO_STORAGE(acc, OUT_T, TYPE_OUT);
    tensorWriteARM(outputData, index, outValue);
}
