/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%
#define RESCALE_TAIL %rescale_tail%
#if RESCALE_TAIL
#define TAIL_OUT_T %tail_out_t%
#define TAIL_MUL_T %tail_mul_t%
#define TAIL_OUT_LOWEST %tail_out_t_lowest%
#define TAIL_OUT_MAX %tail_out_t_max%
#define OUTPUT_T TAIL_OUT_T
RESCALE_TAIL_DECLARE(3, 4)
#else
#define OUTPUT_T OUT_T
#endif
#define TYPE_IN %in_t_type%
#define TYPE_OUT %out_t_type%

#if IS_FLOAT8(TYPE_IN) || IS_FLOAT8(TYPE_OUT)
    #define COMP_T float16_t
#elif IS_BFLOAT(TYPE_IN) || IS_BFLOAT(TYPE_OUT)
    #define COMP_T float
#else
    #define COMP_T OUT_T
#endif

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint1;
    int32_t inputZeroPoint2;
} pushConstants;

layout(set = 0, binding = 0) uniform tensorARM<OUTPUT_T, 3> outputData;   // [N, H, W]
layout(set = 1, binding = 0) uniform tensorARM<IN_T, 3> inputData1;    // [N, H, C]
layout(set = 2, binding = 0) uniform tensorARM<IN_T, 3> inputData2;    // [N, C, W]

void main() {
    const int inputZeroPoint1 = PUSH_INT(0, inputZeroPoint1);
    const int inputZeroPoint2 = PUSH_INT(1, inputZeroPoint2);

#if IS_FLOAT(TYPE_IN) || IS_REDUCED_FLOAT(TYPE_IN)
    uint[3] index;
    getDispatchIndex3(outputData, index);
#else
    uint[3] shape = uint[](tensorSizeARM(outputData, 0), tensorSizeARM(outputData, 1),
                           tensorSizeARM(outputData, 2));
    uint[3] index;
    getVectorIndex(index, shape)
#endif

    uint on = index[0];
    uint oy = index[1];
    uint ox = index[2];

#if IS_FLOAT(TYPE_IN) || IS_REDUCED_FLOAT(TYPE_IN)
    COMP_T acc = COMP_T(0);
#else
    COMP_T acc[4] = COMP_T[4](COMP_T(0), COMP_T(0), COMP_T(0), COMP_T(0));
#endif

    const uint IC = tensorSizeARM(inputData1, 2);

    uint c = 0;
    for (; c + 3 < IC; c += 4) {
        IN_T value1[4];
        tensorReadARM(inputData1, uint[](on, oy, c), value1);

#if IS_FLOAT(TYPE_IN) || IS_REDUCED_FLOAT(TYPE_IN)
        IN_T value20, value21, value22, value23;
        tensorReadARM(inputData2, uint[](on, c, ox), value20);
        tensorReadARM(inputData2, uint[](on, c + 1, ox), value21);
        tensorReadARM(inputData2, uint[](on, c + 2, ox), value22);
        tensorReadARM(inputData2, uint[](on, c + 3, ox), value23);
        IN_T value2[4] = {value20, value21, value22, value23};

        for (uint idx = 0; idx < 4; ++idx) {
            COMP_T val1 = DECODE_STORAGE_TO_COMP(value1[idx], TYPE_IN, COMP_T) - COMP_T(inputZeroPoint1);
            COMP_T val2 = DECODE_STORAGE_TO_COMP(value2[idx], TYPE_IN, COMP_T) - COMP_T(inputZeroPoint2);
            acc += val1 * val2;
        }
#else
        for (uint idx = 0; idx < 4; ++idx) {
            COMP_T val1 = DECODE_STORAGE_TO_COMP(value1[idx], TYPE_IN, COMP_T) - COMP_T(inputZeroPoint1);

            IN_T value2[4];
            tensorReadARM(inputData2, uint[](on, c + idx, ox), value2);

            for (uint k = 0; k < 4; ++k) {
                COMP_T val2 = DECODE_STORAGE_TO_COMP(value2[k], TYPE_IN, COMP_T) - COMP_T(inputZeroPoint2);
                acc[k] += val1 * val2;
            }
        }
#endif
    }

    for (; c < IC; ++c) {
        IN_T v1;
        tensorReadARM(inputData1, uint[](on, oy, c), v1);
        COMP_T val1 = DECODE_STORAGE_TO_COMP(v1, TYPE_IN, COMP_T) - COMP_T(inputZeroPoint1);

#if IS_FLOAT(TYPE_IN) || IS_REDUCED_FLOAT(TYPE_IN)
        IN_T v2;
        tensorReadARM(inputData2, uint[](on, c, ox), v2);
        acc += val1 * (DECODE_STORAGE_TO_COMP(v2, TYPE_IN, COMP_T) - COMP_T(inputZeroPoint2));
#else
        IN_T value2[4];
        tensorReadARM(inputData2, uint[](on, c, ox), value2);

        for (uint k = 0; k < 4; ++k) {
            COMP_T val2 = DECODE_STORAGE_TO_COMP(value2[k], TYPE_IN, COMP_T) - COMP_T(inputZeroPoint2);
            acc[k] += val1 * val2;
        }
#endif
    }

#if IS_FLOAT(TYPE_IN) || IS_REDUCED_FLOAT(TYPE_IN)
    OUT_T outValue = ENCODE_COMP_TO_STORAGE(acc, OUT_T, TYPE_OUT);
#if RESCALE_TAIL
    TAIL_OUT_T tailValue;
    rescaleTail(outValue, ox, tailValue)
    tensorWriteARM(outputData, index, tailValue);
#else
    tensorWriteARM(outputData, index, outValue);
#endif
#else
    OUT_T outValue[4];
    for (uint k = 0; k < 4; ++k) {
        outValue[k] = ENCODE_COMP_TO_STORAGE(acc[k], OUT_T, TYPE_OUT);
    }
#if RESCALE_TAIL
    TAIL_OUT_T tailValue[4];
    for (uint k = 0; k < 4; ++k) {
        rescaleTail(outValue[k], ox + k, tailValue[k])
    }
    tensorWriteARM(outputData, index, tailValue);
#else
    tensorWriteARM(outputData, index, outValue);
#endif
#endif
}
