/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define STORAGE_T %in_out_t%
#define ACC_T %acc_t%
#define TYPE_IN_OUT %in_out_t_type%
#define MIN %in_out_t_lowest%
#define MAX %in_out_t_max%

#if IS_BFLOAT(TYPE_IN_OUT)
    #define COMP_T float
#else
    #define COMP_T ACC_T
#endif

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint;
    int32_t outputZeroPoint;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<STORAGE_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<STORAGE_T, RANK> inputData;

void main() {
    uint[RANK] index;
    getDispatchIndex(outputData, index);

    STORAGE_T valueRaw;
    tensorReadARM(inputData, index, valueRaw);

    COMP_T value = DECODE_STORAGE_TO_COMP(valueRaw, TYPE_IN_OUT, COMP_T);
    COMP_T res = COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_0 : pushConstants.inputZeroPoint)) - value + COMP_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_1 : pushConstants.outputZeroPoint));

#if IS_BFLOAT(TYPE_IN_OUT)
    COMP_T outValue = isnan(float(value)) ? value : (isinf(float(value)) ? COMP_T(-value) : res);
#else
    COMP_T outValue =
        isnan(float(value)) ? value : (isinf(float(value)) ? COMP_T(-value) : clamp(res, COMP_T(MIN), COMP_T(MAX)));
#endif

    tensorWriteARM(outputData, index, ENCODE_COMP_TO_STORAGE(outValue, STORAGE_T, TYPE_IN_OUT));
}
