/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_OUT_T %in_out_t%
#define TYPE_IN_OUT %in_out_t_type%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    DOUBLE padConst;
    int32_t padConstInt;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<IN_OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_OUT_T, RANK> inputData;
layout(set = 2, binding = 0) uniform tensorARM<int32_t, 1> paddingData;

void main() {
    uint[RANK] shape;
    getShape(shape, outputData)
    uint[RANK] index;
    getVectorIndex(index, shape)

    uint[RANK] inputShape;
    getShape(inputShape, inputData);

    uint[RANK] inputIndex;
    bool isPad = false;
    for (uint i = 0; i < RANK; i++) {
        int32_t padding;
        tensorReadARM(paddingData, uint[1](2*i), padding);

        inputIndex[i] = index[i] - padding;
        if (i + 1 < RANK && inputIndex[i] >= inputShape[i]) {
            isPad = true;
        }
    }

#if (TYPE_IN_OUT == TYPE_INT32)
    const IN_OUT_T padValue = IN_OUT_T(pushConstants.padConstInt);
#else
    const IN_OUT_T padValue = ENCODE_COMP_TO_STORAGE(pushConstants.padConst, IN_OUT_T, TYPE_IN_OUT);
#endif

    const uint lastInput = inputIndex[RANK - 1];
    IN_OUT_T value[4];

    if (!isPad && lastInput + 3u >= lastInput && lastInput + 3u < inputShape[RANK - 1]) {
        tensorReadARM(inputData, inputIndex, value);
    } else {
        for (uint k = 0; k < 4; k++) {
            inputIndex[RANK - 1] = lastInput + k;
            if (isPad || inputIndex[RANK - 1] >= inputShape[RANK - 1]) {
                value[k] = padValue;
            } else {
                tensorReadARM(inputData, inputIndex, value[k]);
            }
        }
    }

    tensorWriteARM(outputData, index, value);
}
