/*
 * SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define STORAGE_T %in_out_t%
#define TYPE_IN_OUT %in_out_t_type%

#define COMP_T %in_out_t_comp%
#define IN_OUT_T COMP_T

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    uint axis;
    uint nanMode;
} pushConstants;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<STORAGE_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<STORAGE_T, RANK> inputData;

void main() {
    uint[RANK] index;
    getDispatchIndex(outputData, index);

    const uint dim = index[(PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_0) : pushConstants.axis)];
    COMP_T result = COMP_T(%init%);

    uint[RANK] inputShape;
    getShape(inputShape, inputData);

    for (uint i = 0; i < inputShape[(PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_0) : pushConstants.axis)]; i++) {
        index[(PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_0) : pushConstants.axis)] = i;

#if IS_REDUCED_FLOAT(TYPE_IN_OUT)
        STORAGE_T rawValue;
        tensorReadARM(inputData, index, rawValue);
        COMP_T value = DECODE_STORAGE_TO_COMP(rawValue, TYPE_IN_OUT, COMP_T);
#else
        COMP_T value;
        tensorReadARM(inputData, index, value);
#endif

#if (IS_FLOAT(TYPE_IN_OUT) || IS_REDUCED_FLOAT(TYPE_IN_OUT))
        if (isnan(value)) {
            if ((PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_1) : pushConstants.nanMode) == NAN_MODE_IGNORE) {
                // Ignore value and continue
                continue;
            }
            if ((PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_1) : pushConstants.nanMode) == NAN_MODE_PROPAGATE) {
                // If any value is NaN, then the result must be NaN
                result = value;
                break;
            }
        }
#endif

        result = %operation%;
    }

    index[(PUSH_WORDS_VALID != 0 ? uint(PUSH_WORD_0) : pushConstants.axis)] = dim;

#if IS_REDUCED_FLOAT(TYPE_IN_OUT)
    tensorWriteARM(outputData, index, ENCODE_COMP_TO_STORAGE(result, STORAGE_T, TYPE_IN_OUT));
#else
    tensorWriteARM(outputData, index, STORAGE_T(result));
#endif
}
