/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_OUT_T %in_out_t%

layout(local_size_x = %warpX%) in;

layout(constant_id = 0) const uint32_t RANK_IN = RANK_MAX;
layout(constant_id = 1) const uint32_t RANK_OUT = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<IN_OUT_T, RANK_OUT> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_OUT_T, RANK_IN> inputData;

void main() {
    uint[RANK_OUT] shape;
    getShape(shape, outputData)
    uint[RANK_OUT] index;
    getVectorIndex(index, shape)

    uint offset = 0;
    for (uint i = 0; i < RANK_OUT; i++) {
        offset = offset * shape[i] + index[i];
    }

    uint[RANK_IN] inputShape;
    getShape(inputShape, inputData);

    uint[RANK_IN] inputIndex;
    offsetToIndex(inputShape, offset, inputIndex)

    IN_OUT_T value[4];
    if (inputIndex[RANK_IN - 1] + 3u < inputShape[RANK_IN - 1]) {
        tensorReadARM(inputData, inputIndex, value);
    } else {
        for (uint k = 0; k < 4; k++) {
            uint remainder = offset + k;
            for (int i = int(RANK_IN) - 1; i >= 0; i--) {
                inputIndex[i] = remainder % inputShape[i];
                remainder /= inputShape[i];
            }

            value[k] = IN_OUT_T(0);
            if (remainder == 0) {
                tensorReadARM(inputData, inputIndex, value[k]);
            }
        }
    }

    tensorWriteARM(outputData, index, value);
}
