/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_OUT_T %in_out_t%

layout(local_size_x = %warpX%) in;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<IN_OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<uint8_t, RANK> inputData1;
layout(set = 2, binding = 0) uniform tensorARM<IN_OUT_T, RANK> inputData2;
layout(set = 3, binding = 0) uniform tensorARM<IN_OUT_T, RANK> inputData3;

void main() {
    uint[RANK] shape;
    getShape(shape, outputData)
    uint[RANK] index;
    getVectorIndex(index, shape)

    uint[RANK] inputShape;
    uint[RANK] inputIndex;

    uint8_t value1[4];
    getShape(inputShape, inputData1);
    applyBroadcast(inputShape, index, inputIndex);
    if (inputShape[RANK - 1] == 1u) {
        uint8_t broadcast;
        tensorReadARM(inputData1, inputIndex, broadcast);
        value1 = uint8_t[4](broadcast, broadcast, broadcast, broadcast);
    } else {
        tensorReadARM(inputData1, inputIndex, value1);
    }

    IN_OUT_T value2[4];
    getShape(inputShape, inputData2);
    applyBroadcast(inputShape, index, inputIndex);
    if (inputShape[RANK - 1] == 1u) {
        IN_OUT_T broadcast;
        tensorReadARM(inputData2, inputIndex, broadcast);
        value2 = IN_OUT_T[4](broadcast, broadcast, broadcast, broadcast);
    } else {
        tensorReadARM(inputData2, inputIndex, value2);
    }

    IN_OUT_T value3[4];
    getShape(inputShape, inputData3);
    applyBroadcast(inputShape, index, inputIndex);
    if (inputShape[RANK - 1] == 1u) {
        IN_OUT_T broadcast;
        tensorReadARM(inputData3, inputIndex, broadcast);
        value3 = IN_OUT_T[4](broadcast, broadcast, broadcast, broadcast);
    } else {
        tensorReadARM(inputData3, inputIndex, value3);
    }

    IN_OUT_T result[4];
    for (uint k = 0; k < 4; k++) {
        result[k] = value1[k] != 0 ? value2[k] : value3[k];
    }

    tensorWriteARM(outputData, index, result);
}
