/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%

layout(local_size_x = %warpX%) in;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_T, RANK> inputData;
layout(set = 2, binding = 0) uniform tensorARM<IN_T, 1> tableData;

int32_t lookup(int8_t value) {
    IN_T tableValue;
    tensorReadARM(tableData, uint[](value + 128), tableValue);

    return tableValue;
}

int32_t lookup(int16_t value) {
    int32_t index = (int32_t(value) + 32768) >> 7;
    int32_t fraction = value & 0x7f;

    IN_T tableValue[2];
    tensorReadARM(tableData, uint[](index), tableValue);

    int32_t base = tableValue[0];
    int32_t next = tableValue[1];
    int32_t slope = next - base;
    int32_t result = (base << 7) + slope * fraction;

    return result;
}

void main() {
    uint[RANK] shape;
    if (DISPATCH_RANK == uint(RANK)) {
        const uint dispatchShape[6] = uint[](DISPATCH_SHAPE_0, DISPATCH_SHAPE_1, DISPATCH_SHAPE_2, DISPATCH_SHAPE_3,
                                             DISPATCH_SHAPE_4, DISPATCH_SHAPE_5);
        for (uint i = 0; i < RANK; i++) {
            shape[i] = dispatchShape[i];
        }
    } else {
        getShape(shape, outputData);
    }

    const uint groups = (shape[RANK - 1] + 3u) / 4u;

    uint dispatchOffset = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * gl_NumWorkGroups.x * gl_WorkGroupSize.x;
    uint[RANK] index;
    index[RANK - 1] = (dispatchOffset % groups) * 4u;
    dispatchOffset /= groups;
    for (int i = int(RANK) - 2; i >= 0; i--) {
        index[i] = dispatchOffset % shape[i];
        dispatchOffset /= shape[i];
    }

    if (dispatchOffset > 0) {
        return;
    }

    IN_T value[4];
    tensorReadARM(inputData, index, value);

    OUT_T outValue[4];
    for (uint k = 0; k < 4; k++) {
        outValue[k] = OUT_T(lookup(value[k]));
    }

    tensorWriteARM(outputData, index, outValue);
}
