/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t_storage%
#define OUT_T %out_t_storage%
#define TYPE_IN %in_t_type%

// TOSA table indices and entries are signed, regardless of the tensor storage format.
#if TYPE_IN == TYPE_INT8 || TYPE_IN == TYPE_UINT8
    #define COMP_T int8_t
#else
    #define COMP_T int16_t
#endif

layout(local_size_x = %warpX%) in;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_T, RANK> inputData;
layout(set = 2, binding = 0) uniform tensorARM<IN_T, 1> tableData;

int32_t lookup(int8_t value) {
    IN_T tableValue;
    tensorReadARM(tableData, uint[](value + 128), tableValue);

    return int32_t(COMP_T(tableValue));
}

int32_t lookup(int16_t value) {
    int32_t index = (int32_t(value) + 32768) >> 7;
    int32_t fraction = value & 0x7f;

    IN_T tableValue[2];
    tensorReadARM(tableData, uint[](index), tableValue);

    int32_t base = int32_t(COMP_T(tableValue[0]));
    int32_t next = int32_t(COMP_T(tableValue[1]));
    int32_t slope = next - base;
    int32_t result = (base << 7) + slope * fraction;

    return result;
}

void main() {
    uint[RANK] shape;
    getShape(shape, outputData)
    uint[RANK] index;
    getVectorIndex(index, shape)

    IN_T value[4];
    tensorReadARM(inputData, index, value);

    OUT_T outValue[4];
    for (uint k = 0; k < 4; k++) {
        outValue[k] = OUT_T(lookup(COMP_T(value[k])));
    }

    tensorWriteARM(outputData, index, outValue);
}
