/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_OUT_T %in_out_t%

layout(local_size_x = %warpX%) in;

layout(constant_id = 0) const uint32_t RANK = RANK_MAX;

layout(set = 0, binding = 0) uniform tensorARM<IN_OUT_T, RANK> outputData;
layout(set = 1, binding = 0) uniform tensorARM<IN_OUT_T, RANK> inputData;

void main() {
    uint[RANK] shape;
    getShape(shape, outputData)
    uint[RANK] index;
    getVectorIndex(index, shape)

    uint[RANK] inputShape;
    getShape(inputShape, inputData);

    uint[RANK] inputIndex;
    for (uint i = 0; i < RANK; i++) {
        inputIndex[i] = index[i] % inputShape[i];
    }

    IN_OUT_T value[4];
    if (inputIndex[RANK - 1] + 3u < inputShape[RANK - 1]) {
        tensorReadARM(inputData, inputIndex, value);
    } else {
        for (uint k = 0; k < 4; k++) {
            inputIndex[RANK - 1] = (index[RANK - 1] + k) % inputShape[RANK - 1];
            tensorReadARM(inputData, inputIndex, value[k]);
        }
    }

    tensorWriteARM(outputData, index, value);
}
