/*
 * SPDX-FileCopyrightText: Copyright 2023-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 */

#define IN_T %in_t%
#define OUT_T %out_t%
#define WEIGHT_T %weight_t%
#define TYPE_IN %in_t_type%
#define TYPE_WEIGHT %weight_t_type%
#define TYPE_OUT %out_t_type%
#define TYPE_ACC %acc_t_type%
#define ACC_T %acc_t%

layout(local_size_x = %warpX%) in;

layout(push_constant) uniform PushConstants {
    int32_t inputZeroPoint;
    int32_t weightZeroPoint;
    int32_t pad[4];
    int32_t stride[2];
} pushConstants;

layout(set = 0, binding = 0) uniform tensorARM<OUT_T, 4> outputData;       // [N, OH, OW, OC]
layout(set = 1, binding = 0) uniform tensorARM<IN_T, 4> inputData;         // [N, IH, IW, IC]
layout(set = 2, binding = 0) uniform tensorARM<WEIGHT_T, 4> weightsData;   // [OC, KH, KW, IC]
layout(set = 3, binding = 0) uniform tensorARM<OUT_T, 1> biasesData;       // [BC]

void main() {
    uint[4] index;
    getDispatchIndex4(outputData, index);

    const uint n = index[0];
    const uint oy = index[1];
    const uint ox = index[2];
    const uint oc = index[3];

    OUT_T tempAcc;
    tensorReadARM(biasesData, uint[](tensorSizeARM(biasesData, 0) == 1 ? 0 : oc), tempAcc);
    ACC_T acc = CONV_TO_ACC_BIAS(tempAcc);

    for (uint ky = 0; ky < tensorSizeARM(weightsData, 1); ky++) {
        for (uint kx = 0; kx < tensorSizeARM(weightsData, 2); kx++) {
            int iy = int(oy) - (PUSH_WORDS_VALID != 0 ? int[4](PUSH_WORD_2, PUSH_WORD_3, PUSH_WORD_4, PUSH_WORD_5)[0] : pushConstants.pad[0]) - int(ky);
            int ix = int(ox) - (PUSH_WORDS_VALID != 0 ? int[4](PUSH_WORD_2, PUSH_WORD_3, PUSH_WORD_4, PUSH_WORD_5)[2] : pushConstants.pad[2]) - int(kx);

            if (((iy % (PUSH_WORDS_VALID != 0 ? int[2](PUSH_WORD_6, PUSH_WORD_7)[0] : pushConstants.stride[0])) == 0) && ((ix % (PUSH_WORDS_VALID != 0 ? int[2](PUSH_WORD_6, PUSH_WORD_7)[1] : pushConstants.stride[1])) == 0)) {
                iy /= (PUSH_WORDS_VALID != 0 ? int[2](PUSH_WORD_6, PUSH_WORD_7)[0] : pushConstants.stride[0]);
                ix /= (PUSH_WORDS_VALID != 0 ? int[2](PUSH_WORD_6, PUSH_WORD_7)[1] : pushConstants.stride[1]);

                if ((iy >= 0) && (ix >= 0) &&
                    (uint(iy) < tensorSizeARM(inputData, 1)) &&
                    (uint(ix) < tensorSizeARM(inputData, 2))) {
                    const uint IC = tensorSizeARM(inputData, 3);
                    for (uint ic = 0; ic < IC; ++ic) {
                        IN_T inV;
                        WEIGHT_T wV;
                        tensorReadARM(inputData, uint[](n, uint(iy), uint(ix), ic), inV);
                        tensorReadARM(weightsData, uint[](oc, ky, kx, ic), wV);

                        ACC_T inAcc = CONV_TO_ACC_INPUT(inV) - ACC_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_0 : pushConstants.inputZeroPoint));
                        ACC_T wAcc = CONV_TO_ACC_WEIGHT(wV) - ACC_T((PUSH_WORDS_VALID != 0 ? PUSH_WORD_1 : pushConstants.weightZeroPoint));
                        acc += inAcc * wAcc;
                    }
                }
            }
        }
    }

    tensorWriteARM(outputData, index, OUT_T(CONV_ACC_TO_OUT(acc)));
}
